/**
 * Gemini Image Generation Provider
 * Uses Google's Gemini API with Imagen models for image generation
 */

export interface GeminiImageConfig {
  apiKey: string;
  model?: string; // Accept any Gemini model dynamically
}

export interface GeneratedImage {
  url: string;
  revisedPrompt?: string;
}

export class GeminiImageProvider {
  private config: GeminiImageConfig;
  private baseUrl = 'https://generativelanguage.googleapis.com/v1beta';

  constructor(config: GeminiImageConfig) {
    this.config = {
      model: 'gemini-2.0-flash-exp',
      ...config,
    };
  }

  async generateImage(prompt: string): Promise<GeneratedImage> {
    const model = this.config.model || 'gemini-2.0-flash-exp';
    
    // Imagen models use a different API endpoint
    // All other Gemini models use the generateContent endpoint
    if (model.startsWith('imagen-')) {
      return this.generateWithImagen(prompt);
    } else {
      // All Gemini models (gemini-2.0-flash-exp, gemini-1.5-pro, gemini-2.5-flash, etc.)
      return this.generateWithGemini(prompt);
    }
  }

  private async generateWithGemini(prompt: string): Promise<GeneratedImage> {
    const model = this.config.model || 'gemini-2.0-flash-exp';
    const url = `${this.baseUrl}/models/${model}:generateContent?key=${this.config.apiKey}`;
    
    console.log(`Calling Gemini API for image generation with model: ${model}`);
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `Generate an image: ${prompt}. Return only the image, no text description.`
              }
            ]
          }
        ],
        generationConfig: {
          responseModalities: ['image', 'text'],
        }
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: { message: 'Unknown error' } }));
      console.error('Gemini API error response:', errorData);
      
      // Provide more helpful error messages
      const errorMessage = errorData.error?.message || `Gemini API error: ${response.status}`;
      if (response.status === 400 && errorMessage.includes('responseModalities')) {
        throw new Error(`Model "${model}" does not support image generation. Try a different model like "gemini-2.0-flash-exp".`);
      }
      throw new Error(errorMessage);
    }

    const data = await response.json();
    console.log('Gemini API response structure:', JSON.stringify(data, null, 2).slice(0, 500));
    
    // Extract image from response
    const candidates = data.candidates || [];
    if (candidates.length === 0) {
      // Check if there was a content filter block
      if (data.promptFeedback?.blockReason) {
        throw new Error(`Image generation blocked: ${data.promptFeedback.blockReason}`);
      }
      throw new Error('No image generated by Gemini. The model may not support image generation.');
    }

    const parts = candidates[0]?.content?.parts || [];
    const imagePart = parts.find((p: any) => p.inlineData?.mimeType?.startsWith('image/'));
    
    if (!imagePart?.inlineData?.data) {
      // If no image part, check if there's text explaining why
      const textPart = parts.find((p: any) => p.text);
      if (textPart?.text) {
        throw new Error(`Model returned text instead of image: "${textPart.text.slice(0, 100)}...". This model may not support image generation.`);
      }
      throw new Error('No image data in Gemini response. The model may not support image generation with responseModalities.');
    }

    // Return base64 data URL
    const mimeType = imagePart.inlineData.mimeType || 'image/png';
    const base64Data = imagePart.inlineData.data;
    
    return {
      url: `data:${mimeType};base64,${base64Data}`,
      revisedPrompt: prompt,
    };
  }

  private async generateWithImagen(prompt: string): Promise<GeneratedImage> {
    const url = `${this.baseUrl}/models/${this.config.model}:generateImage?key=${this.config.apiKey}`;
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: {
          text: prompt
        },
        image: {
          numberOfImages: 1,
          aspectRatio: '1:1',
        },
        safetyFilterLevel: 'BLOCK_ONLY_HIGH',
        personGeneration: 'ALLOW_ADULT',
      }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: { message: 'Unknown error' } }));
      throw new Error(error.error?.message || `Imagen API error: ${response.status}`);
    }

    const data = await response.json();
    
    // Extract image from response
    const images = data.images || [];
    if (images.length === 0) {
      throw new Error('No image generated by Imagen');
    }

    const imageData = images[0];
    
    // Imagen returns base64 encoded image
    if (imageData.bytesBase64Encoded) {
      return {
        url: `data:image/png;base64,${imageData.bytesBase64Encoded}`,
        revisedPrompt: prompt,
      };
    }

    // Or it might return a GCS URI that we'd need to convert
    if (imageData.gcsUri) {
      throw new Error('GCS URI responses not yet supported. Please use a different model.');
    }

    throw new Error('Unexpected Imagen response format');
  }
}

